workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Générer et patcher le Podfile AVANT tout build
        script: |
          cd ios
          rm -f Podfile
          cd ..
          flutter pub get
          flutter build ios --no-codesign || true
          cd ios
          sed -i.bak 's/platform :ios, .*/platform :ios, "13.0"/' Podfile
      - name: Build iOS release
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa