workflows:
  ios-build:
    name: iOS Build
    environment:
      groups:
        - YapluCa
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain for codesigning
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files com.yapluca.app --type IOS_APP_STORE --create
      - name: Use system default keychain
        script: |
          keychain add-certificates
      - name: Set up code signing on Xcode project
        script: |
          xcode-project use-profiles
      - name: Flutter pub get
        script: flutter pub get
      - name: Build iOS release
        script: flutter build ios --release
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa --workspace "Runner.xcworkspace" --scheme "Runner"
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true