platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return []
  end
  generated_key_values = []
  File.foreach(file_abs_path) do |line|
    line = line.strip
    if line.length == 0 || line[0] == '#'
      next
    end
    key_value = line.split(separator)
    if key_value.length == 2
      generated_key_values.push([key_value[0].strip, key_value[1].strip])
    end
  end
  return generated_key_values
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
